"""
stores/ledger_propagator.py
===========================
P2 — Shared Sector + Market Ledger Propagation.

Responsibility: route lessons generated by the FeedbackAgent to the correct
shared ledgers based on their scope.

Write path (called from daily_review.py Step 6):

    lesson.scope == "stock_specific"
        └── ticker_learning_ledger only (no propagation)

    lesson.scope == "sector_wide"
        ├── ticker_learning_ledger  (source record, already saved)
        └── sector/_shared_ledger.json

    lesson.scope == "market_wide"
        ├── ticker_learning_ledger  (source record, already saved)
        ├── sector/_shared_ledger.json
        └── _market_ledger.json

Cross-ticker confidence boost:
    Each NEW ticker independently confirming an existing shared lesson earns
    that lesson a +0.05 confidence boost. This prevents single-ticker noise
    from masquerading as sector truth — a lesson needs multiple tickers to
    reach high confidence.

Confidence blending (for repeated patterns from the same ticker):
    new_conf = 0.7 × existing_conf + 0.3 × incoming_conf
"""

from __future__ import annotations

import json
import logging
from datetime import date
from pathlib import Path

from core.config import settings
from core.intelligence.rl.provenance import merge_evidence
from core.schemas.feedback import LearningLedger, Lesson

logger = logging.getLogger(__name__)


def propagate_lesson_to_ledger(
    lesson: Lesson,
    shared_ledger: LearningLedger,
    source_ticker: str,
) -> str | None:
    """
    Merge one lesson into a shared (sector or market) ledger in-place.

    - Pattern already present → blend confidence, apply cross-ticker boost if
      this is the first time source_ticker confirms it, update last_seen.
    - Pattern absent → create a new entry with contributing_tickers=[source_ticker].

    Returns the lesson_id of the created/updated entry, or None on failure.
    """
    today_str = date.today().isoformat()

    existing = shared_ledger.find_by_pattern(lesson.pattern)
    if existing is not None:
        # Blend confidence — weighted average biased toward accumulated signal
        existing.confidence = round(
            settings.RL_LESSON_BLEND_EXISTING * existing.confidence
            + settings.RL_LESSON_BLEND_INCOMING * lesson.confidence,
            4,
        )
        existing.occurrences += 1
        existing.last_seen = today_str

        # Cross-ticker boost: only when a genuinely new ticker confirms the lesson.
        # This prevents one highly active ticker from dominating shared confidence.
        contributing = existing.contributing_tickers or []
        if source_ticker not in contributing:
            existing.contributing_tickers = contributing + [source_ticker]
            existing.confidence = min(
                1.0,
                round(existing.confidence + settings.RL_CROSS_TICKER_BOOST, 4),
            )
            logger.info(
                "[LedgerPropagator] Cross-ticker boost +%.2f for pattern '%s' "
                "(confirmed by %s, total tickers: %d)",
                settings.RL_CROSS_TICKER_BOOST,
                lesson.pattern,
                source_ticker,
                len(existing.contributing_tickers),
            )

        # Widen scope if the incoming lesson implies broader applicability
        _rank = {"stock_specific": 0, "sector_wide": 1, "market_wide": 2}
        if _rank.get(lesson.scope, 0) > _rank.get(existing.scope, 0):
            existing.scope = lesson.scope

        # F3: a shared lesson is what other tickers inherit, so it carries the
        # provenance of every ticker that confirmed it, not just the first.
        existing.evidence = merge_evidence(
            existing.evidence, lesson.evidence, settings.RL_LESSON_EVIDENCE_MAX_ITEMS)

        logger.info(
            "[LedgerPropagator] Updated shared lesson %s "
            "(pattern='%s', conf=%.3f, tickers=%s, occurrences=%d)",
            existing.lesson_id,
            existing.pattern,
            existing.confidence,
            existing.contributing_tickers,
            existing.occurrences,
        )
        return existing.lesson_id

    # New pattern in this shared ledger
    new_id = shared_ledger.next_lesson_id()
    shared_ledger.lessons.append(
        Lesson(
            lesson_id=new_id,
            date_learned=today_str,
            category=lesson.category,
            pattern=lesson.pattern,
            observation=lesson.observation,
            rule=lesson.rule,
            confidence=lesson.confidence,
            occurrences=1,
            still_valid=True,
            scope=lesson.scope,
            last_seen=today_str,
            contributing_tickers=[source_ticker],
            evidence=list(lesson.evidence),      # F3 provenance follows the lesson
        )
    )
    logger.info(
        "[LedgerPropagator] Added new shared lesson %s "
        "(pattern='%s', scope=%s, source=%s)",
        new_id,
        lesson.pattern,
        lesson.scope,
        source_ticker,
    )
    return new_id


def propagate_lessons(
    ticker: str,
    updated_ledger: LearningLedger,
    sector_ledger: LearningLedger,
    market_ledger: LearningLedger,
    lesson_ids: list[str],
) -> tuple[LearningLedger, LearningLedger]:
    """
    Route the lessons touched in this review cycle to the shared ledgers.

    Only lessons whose lesson_id is in lesson_ids (i.e. created or updated
    during this daily review) are propagated. Lessons already present in the
    ledger from previous cycles are NOT re-propagated.

    scope=stock_specific  → no propagation
    scope=sector_wide     → sector_ledger only
    scope=market_wide     → sector_ledger AND market_ledger

    Parameters
    ----------
    ticker : str
        The source ticker (used to populate contributing_tickers).
    updated_ledger : LearningLedger
        The ticker's learning ledger after this review cycle's merges.
    sector_ledger : LearningLedger
        The sector-wide shared ledger (mutated in-place).
    market_ledger : LearningLedger
        The market-wide shared ledger (mutated in-place).
    lesson_ids : list[str]
        IDs of lessons created or updated in this cycle.

    Returns
    -------
    (sector_ledger, market_ledger) — both updated in-place and returned.
    """
    if not lesson_ids:
        logger.debug("[LedgerPropagator] No lesson IDs to propagate for %s", ticker)
        return sector_ledger, market_ledger

    id_set = set(lesson_ids)
    sector_updates = 0
    market_updates = 0

    for lesson in updated_ledger.lessons:
        if lesson.lesson_id not in id_set:
            continue
        if lesson.scope == "stock_specific":
            continue

        # sector_wide and market_wide both go to the sector shared ledger
        if lesson.scope in ("sector_wide", "market_wide"):
            propagate_lesson_to_ledger(lesson, sector_ledger, ticker)
            sector_updates += 1

        # market_wide also propagates to the cross-sector market ledger
        if lesson.scope == "market_wide":
            propagate_lesson_to_ledger(lesson, market_ledger, ticker)
            market_updates += 1

    logger.info(
        "[LedgerPropagator] %s — propagated %d lessons to sector ledger, "
        "%d to market ledger",
        ticker,
        sector_updates,
        market_updates,
    )
    return sector_ledger, market_ledger


def build_tiered_lessons_summary(
    ticker_ledger: LearningLedger,
    sector_ledger: LearningLedger,
    market_ledger: LearningLedger,
) -> str:
    """
    Build a 3-tier lessons summary for injection into the FeedbackAgent prompt.

    Tier limits (tuned to keep prompt size reasonable):
      TIER 1 — up to 6 stock-specific lessons (highest effective confidence)
      TIER 2 — up to 3 sector-wide lessons from the shared sector ledger
      TIER 3 — up to 2 market-wide lessons from the shared market ledger

    Lessons with effective_confidence < 0.20 are excluded — they are nearly
    stale and their signal has decayed too far to be actionable.
    """
    from datetime import date as _date
    today = _date.today()
    _min_eff = 0.20

    def _age(lesson: Lesson) -> str:
        ref = lesson.last_seen or lesson.date_learned or ""
        try:
            return f"{(today - _date.fromisoformat(ref)).days}d ago"
        except Exception:
            return "?"

    lines: list[str] = []

    # ── TIER 1: stock-specific ────────────────────────────────────────────────
    t1 = sorted(
        [l for l in ticker_ledger.lessons
         if l.still_valid and l.scope == "stock_specific"
         and ticker_ledger.effective_confidence(l) >= _min_eff],
        key=lambda l: ticker_ledger.effective_confidence(l),
        reverse=True,
    )[:6]
    if t1:
        lines.append("[TIER 1 — stock-specific lessons]")
        for l in t1:
            lines.append(
                f"  {l.lesson_id} [{l.category}] {l.pattern}: {l.rule} "
                f"(eff_conf={ticker_ledger.effective_confidence(l):.2f}, "
                f"seen={l.occurrences}x, last={_age(l)})"
            )

    # ── TIER 2: sector-wide ───────────────────────────────────────────────────
    t2 = sorted(
        [l for l in sector_ledger.lessons
         if l.still_valid
         and sector_ledger.effective_confidence(l) >= _min_eff],
        key=lambda l: sector_ledger.effective_confidence(l),
        reverse=True,
    )[:3]
    if t2:
        lines.append("[TIER 2 — sector-wide lessons (confirmed across multiple tickers)]")
        for l in t2:
            tickers_str = ", ".join(l.contributing_tickers) if l.contributing_tickers else "?"
            lines.append(
                f"  {l.lesson_id} [{l.category}] {l.pattern}: {l.rule} "
                f"(eff_conf={sector_ledger.effective_confidence(l):.2f}, "
                f"confirmed_by=[{tickers_str}], seen={l.occurrences}x, last={_age(l)})"
            )

    # ── TIER 3: market-wide ───────────────────────────────────────────────────
    t3 = sorted(
        [l for l in market_ledger.lessons
         if l.still_valid
         and market_ledger.effective_confidence(l) >= _min_eff],
        key=lambda l: market_ledger.effective_confidence(l),
        reverse=True,
    )[:2]
    if t3:
        lines.append("[TIER 3 — market-wide lessons (cross-sector)]")
        for l in t3:
            tickers_str = ", ".join(l.contributing_tickers) if l.contributing_tickers else "?"
            lines.append(
                f"  {l.lesson_id} [{l.category}] {l.pattern}: {l.rule} "
                f"(eff_conf={market_ledger.effective_confidence(l):.2f}, "
                f"confirmed_by=[{tickers_str}], seen={l.occurrences}x, last={_age(l)})"
            )

    return "\n".join(lines) if lines else "No lessons learned yet."


def downgrade_stale_lessons(
    ledger: "LearningLedger",
    staleness_days: int = 30,
) -> int:
    """
    Downgrade scope for lessons confirmed by only ONE ticker that haven't
    been seen in staleness_days days. Multi-ticker lessons are real signal
    and are never auto-downgraded.

    Rules:
      market_wide  + 1 ticker + inactive >  staleness_days  → sector_wide
      sector_wide  + 1 ticker + inactive > 2×staleness_days → still_valid=False

    Returns number of lessons modified. Mutates ledger in-place.
    """
    from datetime import date as _date

    today = _date.today()
    modified = 0
    for lesson in ledger.lessons:
        if not lesson.still_valid:
            continue
        if len(lesson.contributing_tickers) > 1:
            continue  # multi-ticker = real cross-asset signal, never auto-downgrade
        try:
            days_inactive = (today - _date.fromisoformat(lesson.last_seen)).days
        except Exception:
            continue

        if lesson.scope == "market_wide" and days_inactive > staleness_days:
            lesson.scope = "sector_wide"
            modified += 1
            logger.info(
                "[ledger_propagator] %s: downgraded market_wide → sector_wide "
                "(%d days inactive, 1 ticker)",
                lesson.lesson_id, days_inactive,
            )
        elif lesson.scope == "sector_wide" and days_inactive > staleness_days * 2:
            lesson.still_valid = False
            modified += 1
            logger.info(
                "[ledger_propagator] %s: invalidated sector_wide lesson "
                "(%d days inactive, 1 ticker)",
                lesson.lesson_id, days_inactive,
            )
    return modified


# ---------------------------------------------------------------------------
# RL Intelligence Phase, Component 3 — Stale-lesson archival with resurrection
# ---------------------------------------------------------------------------

def _load_cold_store(cold_store_path: Path) -> list[Lesson]:
    """
    Load the cold-store list of archived lessons from `cold_store_path`.
    Returns [] when the file does not exist or cannot be parsed.
    """
    path = Path(cold_store_path)
    if not path.exists():
        return []
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return [Lesson(**item) for item in data.get("archived_lessons", [])]
    except (json.JSONDecodeError, OSError, ValueError) as exc:
        logger.error("[ledger_propagator] Failed to read cold store %s: %s", path, exc)
        return []


def _save_cold_store(cold_store_path: Path, lessons: list[Lesson], ticker: str = "", sector: str = "") -> None:
    """
    Atomically write the cold-store archived lessons list, following the same
    temp-file-then-rename pattern as PredictionStore._write_json.
    """
    path = Path(cold_store_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "ticker": ticker,
        "sector": sector,
        "archived_lessons": [lesson.model_dump() for lesson in lessons],
    }
    tmp = path.with_suffix(".tmp")
    try:
        tmp.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
        tmp.replace(path)
    except OSError as exc:
        logger.error("[ledger_propagator] Cold store write failed for %s: %s", path, exc)
        try:
            tmp.unlink(missing_ok=True)
        except OSError:
            pass
        raise RuntimeError(f"Cold store write failed for {path}: {exc}") from exc


def archive_stale_lessons(
    ledger: LearningLedger,
    cold_store_path: Path | str,
    conf_floor: float | None = None,
    effectiveness_floor: float | None = None,
    stale_days: int | None = None,
) -> int:
    """
    Archive invalidated, low-value, stale lessons to a per-ticker cold store.

    A lesson is archived only when ALL of the following hold:
      1. lesson.still_valid is False (already invalidated — never archive a
         lesson the system still believes in).
      2. ledger.effective_confidence(lesson) <= conf_floor
         (default settings.ARCHIVE_CONF_FLOOR = 0.12).
      3. effectiveness < effectiveness_floor
         (default settings.ARCHIVE_EFFECTIVENESS_FLOOR = 0.25), where
         effectiveness = correction_counter[pattern] / (correction_counter[pattern]
         + miss_counter[pattern]); 0/0 is treated as 0.0.
      4. days since (last_seen or date_learned) > stale_days
         (default settings.ARCHIVE_STALE_DAYS = 60).

    Archived lessons are appended to the cold-store JSON at `cold_store_path`
    (created if absent) and removed from `ledger.lessons` in-place.

    Returns the number of lessons archived. Mutates `ledger` in-place; does
    NOT save the ledger — callers are responsible for persisting it.
    """
    conf_floor = settings.ARCHIVE_CONF_FLOOR if conf_floor is None else conf_floor
    effectiveness_floor = (
        settings.ARCHIVE_EFFECTIVENESS_FLOOR if effectiveness_floor is None else effectiveness_floor
    )
    stale_days = settings.ARCHIVE_STALE_DAYS if stale_days is None else stale_days

    today = date.today()
    to_archive: list[Lesson] = []
    keep: list[Lesson] = []

    for lesson in ledger.lessons:
        if lesson.still_valid:
            keep.append(lesson)
            continue

        eff_conf = ledger.effective_confidence(lesson)
        if eff_conf > conf_floor:
            keep.append(lesson)
            continue

        correction = ledger.correction_counter.get(lesson.pattern, 0)
        miss = ledger.miss_counter.get(lesson.pattern, 0)
        denom = correction + miss
        effectiveness = (correction / denom) if denom > 0 else 0.0
        if effectiveness >= effectiveness_floor:
            keep.append(lesson)
            continue

        ref_str = lesson.last_seen or lesson.date_learned
        try:
            ref_date = date.fromisoformat(ref_str)
            days_inactive = (today - ref_date).days
        except (ValueError, TypeError):
            keep.append(lesson)
            continue

        if days_inactive <= stale_days:
            keep.append(lesson)
            continue

        to_archive.append(lesson)
        logger.info(
            "[ledger_propagator] Archiving stale lesson %s (pattern='%s', "
            "eff_conf=%.3f, effectiveness=%.3f, days_inactive=%d)",
            lesson.lesson_id, lesson.pattern, eff_conf, effectiveness, days_inactive,
        )

    if not to_archive:
        return 0

    cold_store = _load_cold_store(Path(cold_store_path))
    cold_store.extend(to_archive)
    _save_cold_store(Path(cold_store_path), cold_store, ticker=ledger.ticker, sector=ledger.sector)

    ledger.lessons = keep
    logger.info(
        "[ledger_propagator] %s: archived %d lesson(s) to cold store %s",
        ledger.ticker, len(to_archive), cold_store_path,
    )
    return len(to_archive)


def resurrect_lesson(
    ledger: LearningLedger,
    cold_store_path: Path | str,
    pattern: str,
    semantic_tags: list[str] | None = None,
    new_confidence: float = 0.5,
    min_overlap: int = 2,
) -> Lesson | None:
    """
    Check the cold store for a previously-archived lesson matching `pattern`
    (exact match) or sharing >= min_overlap semantic tags with `semantic_tags`.

    If found:
      - Remove it from the cold store.
      - Restore it to `ledger.lessons` (occurrences/history intact).
      - Set still_valid=True, last_seen=today, invalidation_streak=0,
        clear invalidation_reason/invalidation_date.
      - confidence = max(old_confidence * 0.8, new_confidence).
      - Persist the updated cold store.
      - Return the restored Lesson.

    If not found, returns None and leaves both ledger and cold store untouched.

    Callers should check this BEFORE creating a brand-new Lesson for `pattern`
    — a hit here means "restore instead of duplicate".
    """
    cold_store = _load_cold_store(Path(cold_store_path))
    if not cold_store:
        return None

    semantic_tags = semantic_tags or []
    tag_set = set(semantic_tags)

    match_idx: int | None = None
    for idx, archived in enumerate(cold_store):
        if archived.pattern == pattern:
            match_idx = idx
            break
        if tag_set and archived.semantic_tags:
            overlap = len(tag_set & set(archived.semantic_tags))
            if overlap >= min_overlap:
                match_idx = idx
                break

    if match_idx is None:
        return None

    restored = cold_store.pop(match_idx)
    today_str = date.today().isoformat()
    restored.still_valid = True
    restored.last_seen = today_str
    restored.invalidation_streak = 0
    restored.invalidation_reason = ""
    restored.invalidation_date = ""
    restored.confidence = round(max(restored.confidence * 0.8, new_confidence), 4)

    ledger.lessons.append(restored)
    _save_cold_store(Path(cold_store_path), cold_store, ticker=ledger.ticker, sector=ledger.sector)

    logger.info(
        "[ledger_propagator] Resurrected lesson %s (pattern='%s') from cold store "
        "for %s (confidence=%.3f, occurrences=%d)",
        restored.lesson_id, restored.pattern, ledger.ticker,
        restored.confidence, restored.occurrences,
    )
    return restored
