"""
stores/ledger_propagator.py
===========================
P2 — Shared Sector + Market Ledger Propagation.

Responsibility: route lessons generated by the FeedbackAgent to the correct
shared ledgers based on their scope.

Write path (called from daily_review.py Step 6):

    lesson.scope == "stock_specific"
        └── ticker_learning_ledger only (no propagation)

    lesson.scope == "sector_wide"
        ├── ticker_learning_ledger  (source record, already saved)
        └── sector/_shared_ledger.json

    lesson.scope == "market_wide"
        ├── ticker_learning_ledger  (source record, already saved)
        ├── sector/_shared_ledger.json
        └── _market_ledger.json

Cross-ticker confidence boost:
    Each NEW ticker independently confirming an existing shared lesson earns
    that lesson a +0.05 confidence boost. This prevents single-ticker noise
    from masquerading as sector truth — a lesson needs multiple tickers to
    reach high confidence.

Confidence blending (for repeated patterns from the same ticker):
    new_conf = 0.7 × existing_conf + 0.3 × incoming_conf
"""

from __future__ import annotations

import logging
from datetime import date

from core.schemas.feedback import LearningLedger, Lesson

logger = logging.getLogger(__name__)

# Confidence blend weights when merging a repeated pattern from any ticker.
# 70/30 in favour of the accumulated signal — avoids single-day spikes.
_BLEND_EXISTING = 0.70
_BLEND_INCOMING = 0.30

# Per-new-ticker confidence bonus. Requires the confirming ticker to be new
# (not already in contributing_tickers). Capped at 1.0 after application.
_CROSS_TICKER_BOOST = 0.05


def propagate_lesson_to_ledger(
    lesson: Lesson,
    shared_ledger: LearningLedger,
    source_ticker: str,
) -> str | None:
    """
    Merge one lesson into a shared (sector or market) ledger in-place.

    - Pattern already present → blend confidence, apply cross-ticker boost if
      this is the first time source_ticker confirms it, update last_seen.
    - Pattern absent → create a new entry with contributing_tickers=[source_ticker].

    Returns the lesson_id of the created/updated entry, or None on failure.
    """
    today_str = date.today().isoformat()

    existing = shared_ledger.find_by_pattern(lesson.pattern)
    if existing is not None:
        # Blend confidence — weighted average biased toward accumulated signal
        existing.confidence = round(
            _BLEND_EXISTING * existing.confidence
            + _BLEND_INCOMING * lesson.confidence,
            4,
        )
        existing.occurrences += 1
        existing.last_seen = today_str

        # Cross-ticker boost: only when a genuinely new ticker confirms the lesson.
        # This prevents one highly active ticker from dominating shared confidence.
        contributing = existing.contributing_tickers or []
        if source_ticker not in contributing:
            existing.contributing_tickers = contributing + [source_ticker]
            existing.confidence = min(
                1.0,
                round(existing.confidence + _CROSS_TICKER_BOOST, 4),
            )
            logger.info(
                "[LedgerPropagator] Cross-ticker boost +%.2f for pattern '%s' "
                "(confirmed by %s, total tickers: %d)",
                _CROSS_TICKER_BOOST,
                lesson.pattern,
                source_ticker,
                len(existing.contributing_tickers),
            )

        # Widen scope if the incoming lesson implies broader applicability
        _rank = {"stock_specific": 0, "sector_wide": 1, "market_wide": 2}
        if _rank.get(lesson.scope, 0) > _rank.get(existing.scope, 0):
            existing.scope = lesson.scope

        logger.info(
            "[LedgerPropagator] Updated shared lesson %s "
            "(pattern='%s', conf=%.3f, tickers=%s, occurrences=%d)",
            existing.lesson_id,
            existing.pattern,
            existing.confidence,
            existing.contributing_tickers,
            existing.occurrences,
        )
        return existing.lesson_id

    # New pattern in this shared ledger
    new_id = shared_ledger.next_lesson_id()
    shared_ledger.lessons.append(
        Lesson(
            lesson_id=new_id,
            date_learned=today_str,
            category=lesson.category,
            pattern=lesson.pattern,
            observation=lesson.observation,
            rule=lesson.rule,
            confidence=lesson.confidence,
            occurrences=1,
            still_valid=True,
            scope=lesson.scope,
            last_seen=today_str,
            contributing_tickers=[source_ticker],
        )
    )
    logger.info(
        "[LedgerPropagator] Added new shared lesson %s "
        "(pattern='%s', scope=%s, source=%s)",
        new_id,
        lesson.pattern,
        lesson.scope,
        source_ticker,
    )
    return new_id


def propagate_lessons(
    ticker: str,
    updated_ledger: LearningLedger,
    sector_ledger: LearningLedger,
    market_ledger: LearningLedger,
    lesson_ids: list[str],
) -> tuple[LearningLedger, LearningLedger]:
    """
    Route the lessons touched in this review cycle to the shared ledgers.

    Only lessons whose lesson_id is in lesson_ids (i.e. created or updated
    during this daily review) are propagated. Lessons already present in the
    ledger from previous cycles are NOT re-propagated.

    scope=stock_specific  → no propagation
    scope=sector_wide     → sector_ledger only
    scope=market_wide     → sector_ledger AND market_ledger

    Parameters
    ----------
    ticker : str
        The source ticker (used to populate contributing_tickers).
    updated_ledger : LearningLedger
        The ticker's learning ledger after this review cycle's merges.
    sector_ledger : LearningLedger
        The sector-wide shared ledger (mutated in-place).
    market_ledger : LearningLedger
        The market-wide shared ledger (mutated in-place).
    lesson_ids : list[str]
        IDs of lessons created or updated in this cycle.

    Returns
    -------
    (sector_ledger, market_ledger) — both updated in-place and returned.
    """
    if not lesson_ids:
        logger.debug("[LedgerPropagator] No lesson IDs to propagate for %s", ticker)
        return sector_ledger, market_ledger

    id_set = set(lesson_ids)
    sector_updates = 0
    market_updates = 0

    for lesson in updated_ledger.lessons:
        if lesson.lesson_id not in id_set:
            continue
        if lesson.scope == "stock_specific":
            continue

        # sector_wide and market_wide both go to the sector shared ledger
        if lesson.scope in ("sector_wide", "market_wide"):
            propagate_lesson_to_ledger(lesson, sector_ledger, ticker)
            sector_updates += 1

        # market_wide also propagates to the cross-sector market ledger
        if lesson.scope == "market_wide":
            propagate_lesson_to_ledger(lesson, market_ledger, ticker)
            market_updates += 1

    logger.info(
        "[LedgerPropagator] %s — propagated %d lessons to sector ledger, "
        "%d to market ledger",
        ticker,
        sector_updates,
        market_updates,
    )
    return sector_ledger, market_ledger


def build_tiered_lessons_summary(
    ticker_ledger: LearningLedger,
    sector_ledger: LearningLedger,
    market_ledger: LearningLedger,
) -> str:
    """
    Build a 3-tier lessons summary for injection into the FeedbackAgent prompt.

    Tier limits (tuned to keep prompt size reasonable):
      TIER 1 — up to 6 stock-specific lessons (highest effective confidence)
      TIER 2 — up to 3 sector-wide lessons from the shared sector ledger
      TIER 3 — up to 2 market-wide lessons from the shared market ledger

    The contributing_tickers list is shown for Tier 2/3 so the LLM understands
    how many independent tickers confirmed each sector/market pattern.
    """
    lines: list[str] = []

    # ── TIER 1: stock-specific ────────────────────────────────────────────────
    t1 = sorted(
        [l for l in ticker_ledger.lessons if l.still_valid and l.scope == "stock_specific"],
        key=lambda l: ticker_ledger.effective_confidence(l),
        reverse=True,
    )[:6]
    if t1:
        lines.append("[TIER 1 — stock-specific lessons]")
        for l in t1:
            lines.append(
                f"  {l.lesson_id} [{l.category}] {l.pattern}: {l.rule} "
                f"(eff_conf={ticker_ledger.effective_confidence(l):.2f}, seen={l.occurrences}x)"
            )

    # ── TIER 2: sector-wide ───────────────────────────────────────────────────
    t2 = sorted(
        [l for l in sector_ledger.lessons if l.still_valid],
        key=lambda l: sector_ledger.effective_confidence(l),
        reverse=True,
    )[:3]
    if t2:
        lines.append("[TIER 2 — sector-wide lessons (confirmed across multiple tickers)]")
        for l in t2:
            tickers_str = ", ".join(l.contributing_tickers) if l.contributing_tickers else "?"
            lines.append(
                f"  {l.lesson_id} [{l.category}] {l.pattern}: {l.rule} "
                f"(eff_conf={sector_ledger.effective_confidence(l):.2f}, "
                f"confirmed_by=[{tickers_str}], seen={l.occurrences}x)"
            )

    # ── TIER 3: market-wide ───────────────────────────────────────────────────
    t3 = sorted(
        [l for l in market_ledger.lessons if l.still_valid],
        key=lambda l: market_ledger.effective_confidence(l),
        reverse=True,
    )[:2]
    if t3:
        lines.append("[TIER 3 — market-wide lessons (cross-sector)]")
        for l in t3:
            tickers_str = ", ".join(l.contributing_tickers) if l.contributing_tickers else "?"
            lines.append(
                f"  {l.lesson_id} [{l.category}] {l.pattern}: {l.rule} "
                f"(eff_conf={market_ledger.effective_confidence(l):.2f}, "
                f"confirmed_by=[{tickers_str}], seen={l.occurrences}x)"
            )

    return "\n".join(lines) if lines else "No lessons learned yet."


def downgrade_stale_lessons(
    ledger: "LearningLedger",
    staleness_days: int = 30,
) -> int:
    """
    Downgrade scope for lessons confirmed by only ONE ticker that haven't
    been seen in staleness_days days. Multi-ticker lessons are real signal
    and are never auto-downgraded.

    Rules:
      market_wide  + 1 ticker + inactive >  staleness_days  → sector_wide
      sector_wide  + 1 ticker + inactive > 2×staleness_days → still_valid=False

    Returns number of lessons modified. Mutates ledger in-place.
    """
    from datetime import date as _date

    today = _date.today()
    modified = 0
    for lesson in ledger.lessons:
        if not lesson.still_valid:
            continue
        if len(lesson.contributing_tickers) > 1:
            continue  # multi-ticker = real cross-asset signal, never auto-downgrade
        try:
            days_inactive = (today - _date.fromisoformat(lesson.last_seen)).days
        except Exception:
            continue

        if lesson.scope == "market_wide" and days_inactive > staleness_days:
            lesson.scope = "sector_wide"
            modified += 1
            logger.info(
                "[ledger_propagator] %s: downgraded market_wide → sector_wide "
                "(%d days inactive, 1 ticker)",
                lesson.lesson_id, days_inactive,
            )
        elif lesson.scope == "sector_wide" and days_inactive > staleness_days * 2:
            lesson.still_valid = False
            modified += 1
            logger.info(
                "[ledger_propagator] %s: invalidated sector_wide lesson "
                "(%d days inactive, 1 ticker)",
                lesson.lesson_id, days_inactive,
            )
    return modified
