# ── MIGRATION SHIM ────────────────────────────────────────────────────────────
# Real module: src/backend/shared/schemas/feedback.py
# This shim keeps all existing `from core.schemas.feedback import ...` working
# unchanged during the migration.  Remove once every import is updated.
from backend.shared.schemas.feedback import *  # noqa: F401, F403
from backend.shared.schemas.feedback import (  # explicit re-exports for IDEs
    Direction,
    LessonCategory,
    LessonScope,
    MissType,
    MISS_TYPE_PENALTY_MULTIPLIER,
    LESSON_DECAY_RATES,
    NO_PENALTY_MISS_TYPES,
    MissAnalysis,
    TimingAccuracy,
    RevisedContext,
    ThesisReview,
    FeedbackEntry,
    DailyFeedbackLog,
    AgentAccuracy,
    MonthlyAccuracySnapshot,
    WeightHistoryEntry,
    WeightMemory,
    Lesson,
    MissEvent,
    LearningLedger,
    ConvictionStreak,
    DailyForecast,
    PredictionEnvelope,
    SeasonalPattern,
    SeasonalContext,
    FeedbackAgentInput,
    RawLesson,
    FeedbackAgentOutput,
    RegimeSnapshot,
    BlockDeal,
    BulkDeal,
    OffMarketSignals,
    FnOSnapshot,
)
